version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5433"
    volumes:
    -  \PostgreSQL\12\data
    env_file:
    - docker.env
  build:
    image: postgres:latest
 # pgadmin:
 #links:
  #- postgres:postgres2
   #container_name: pgadmin
    # image: dpage/pgadmin4
    # ports:
     #- "8080:80"
     #volumes:
   #-  C:\Program Files\PostgreSQL\12\data
    # env_file:
     #- docker.env
     #networks:
     #- postgres
 
#networks:
#  postgres:
 #   driver: bridge

    #C:\Program Files\PostgreSQL\12\data